djcrm/urls.py
from django.contrib import admin
from django.contrib.auth.views import (
LoginView, 
LogoutView, 
PasswordResetView, 
PasswordResetDoneView,
PasswordResetConfirmView,
PasswordResetCompleteView
)
from django.urls import path,include
from leads.views import landing_page , LandingPageView, SignupView
from agents.views import AgentListView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPageView.as_view(), name="landing-page"),
    path('leads/', include('leads.urls',namespace="leads")),
    path('agents/', include('agents.urls',namespace="agents")),
    path('signup/',SignupView.as_view(), name="signup"),
    path('reset-password/',PasswordResetView.as_view(), name="reset-password"),
    path('password-reset-done/',PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(), name="password_reset_complete"),


    
    path('login/',LoginView.as_view(), name="login"),
    path('logout/',LogoutView.as_view(), name="logout"),

    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import (
LeadListView,lead_detail, 
LeadDetailView,LeadCreateView,
LeadDeleteView, LeadUpdateView, 
AssignAgentView, CategoryListView,
CategoryDetailView, LeadCategoryUpdateView
)

app_name="leads"

urlpatterns=[
      path('', LeadListView.as_view(), name='lead-list'),
      path('create/', LeadCreateView.as_view(),name='lead-create'),
      path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
      path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead-update'),
      path('<int:pk>/delete/', LeadDeleteView.as_view(),name='lead-delete'),
      path('<int:pk>/assign-agent/', AssignAgentView.as_view(),name='assign-agent'),
      path('categories/', CategoryListView.as_view(),name='category-list'),
      path('categories/<int:pk>/', CategoryDetailView.as_view(),name='category-detail'),
      path('<int:pk>/category/', LeadCategoryUpdateView.as_view(),name='lead-category-update'),

      





      

]

leads/models.py
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    is_organiser = models.BooleanField(default = True)
    is_agent     = models.BooleanField(default = False)


class UserProfile(models.Model):
    user       = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username

class Lead(models.Model):
    first_name   = models.CharField(max_length = 50)
    last_name    = models.CharField(max_length = 50)
    age          = models.IntegerField(default = 14)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent        = models.ForeignKey("Agent",null = True , blank = True, on_delete=models.SET_NULL)
    category     = models.ForeignKey("Category", related_name="leads", null = True , blank = True, on_delete=models.SET_NULL)
    description  = models.TextField()
    date_added   = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=20)
    email        = models.EmailField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    


class Agent(models.Model):
    user         = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    def __str__(self):
        return self.user.email
   
class Category(models.Model):
    name = models.CharField(max_length=30) #new, contacted, converted, unconverted
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)


    def __str__(self):
        return self.name


def post_user_created_signal(sender, instance, created, **kwargs):
    print(instance, created)
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(post_user_created_signal, sender=User)







    
   

    

leads/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Lead, Agent
from django.contrib.auth.forms import UserCreationForm , UsernameField


User = get_user_model()
class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ("first_name",
                  "last_name",
                  "age" ,      
                  "agent", 
                  "description" ,  
                  "phone_number" ,
                  "email" ,   


                     )



class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name  = forms.CharField()
    age        = forms.IntegerField(min_value=0)


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_class = {'username': UsernameField}


class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organisation = request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents


class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'category',
        )

leads/views.py
from django.core.mail import send_mail
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.http import HttpResponse
from .models import Lead , Agent, Category
from .forms import LeadModelForm , CustomUserCreationForm, AssignAgentForm, LeadCategoryUpdateForm
from django.views.generic import TemplateView, ListView , DetailView ,CreateView, UpdateView, DeleteView
from agents.mixins import OrganiserAndLoginRequiredMixin



class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class    = CustomUserCreationForm
   
    def get_success_url(self):
        return reverse("login")


class LandingPageView(TemplateView):
    template_name = "landing.html"


def landing_page(request):
    return render(request, "landing.html")




    

class LeadListView(LoginRequiredMixin, ListView):
    template_name = "leads/lead_list.html"
    context_object_name = "leads"
    def get_queryset(self):
        user = self.request.user
        if user.is_organiser:
            queryset      = Lead.objects.filter(organisation = user.userprofile,  agent__isnull=False)
        else:
            queryset      = Lead.objects.filter(organisation = user.agent.organisation,  agent__isnull=False)
            queryset      = queryset.filter(agent__user = user)
        return queryset
    def get_context_data(self, **kwargs):
        context = super(LeadListView, self).get_context_data(**kwargs)
        user = self.request.user
            
        if user.is_organiser:
            queryset      = Lead.objects.filter(organisation = user.userprofile, agent__isnull=True)
            context.update({
                "unassigned_leads": queryset

            })
        return context
    
     


def lead_detail(request,pk):
   
    lead = Lead.objects.get(id=pk)
    context={
        "lead":lead
    }
   
    return render(request, "leads/lead_details.html",context)


class LeadDetailView(LoginRequiredMixin,DetailView):
    template_name = "leads/lead_details.html"
    context_object_name = "lead"

    def get_queryset(self):
        user = self.request.user
        if user.is_organiser:
            queryset      = Lead.objects.filter(organisation = user.userprofile)
        else:
            queryset      = Lead.objects.filter(organisation = user.agent.organisation)
            queryset = queryset.filter(agent__user = user)
        return queryset

    




def lead_create(request):
    form = LeadModelForm()
    if request.method == "POST":
        form = LeadModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/leads")
    context = {
        "form":form
    }


    return render(request,"leads/lead_create.html",context)

class LeadCreateView(OrganiserAndLoginRequiredMixin, generic.CreateView):
    template_name = "leads/lead_create.html"
    form_class    =  LeadModelForm
    def get_success_url(self):
        return reverse("leads:lead-list")
    
    def form_valid(self,form):
        lead = form.save(commit=False)
        lead.organisation = self.request.user.userprofile
        lead.save()
        send_mail(
            subject="A lead has been created",
            message="Go to the site to see the new lead", 
            from_email="test@test.com", 
            recipient_list=["test2@test.com"]
        )

        return super(LeadCreateView, self).form_valid(form)



#

class LeadUpdateView(OrganiserAndLoginRequiredMixin,UpdateView):
    template_name = "leads/lead_update.html"
    form_class    =  LeadModelForm

    def get_queryset(self):
        user = self.request.user
        return Lead.objects.filter(organisation = user.userprofile)
        
    
    def get_success_url(self):
        return reverse("leads:lead-list")


def lead_delete(request,pk):
    lead = Lead.objects.get(id=pk)
    lead.delete()
    return redirect("/leads")

class LeadDeleteView(OrganiserAndLoginRequiredMixin, DeleteView):
    template_name = "leads/lead_delete.html"
    
    def get_queryset(self):
        user = self.request.user
        return Lead.objects.filter(organisation = user.userprofile)
    def get_success_url(self):
        return reverse("leads:lead-list")



class AssignAgentView(OrganiserAndLoginRequiredMixin, generic.FormView):
    template_name = "leads/assign_agent.html"
    form_class = AssignAgentForm

    def get_form_kwargs(self, **kwargs):
        kwargs = super(AssignAgentView, self).get_form_kwargs(**kwargs)
        kwargs.update({
            "request": self.request
        })
        return kwargs

    def get_success_url(self):
        return reverse("leads:lead-list")

    def form_valid(self, form):
        agent = form.cleaned_data["agent"]
        lead = Lead.objects.get(id=self.kwargs["pk"])
        lead.agent = agent
        lead.save()
        return super(AssignAgentView, self).form_valid(form)


class CategoryListView(LoginRequiredMixin, generic.ListView):
    template_name       = "leads/category_list.html"
    context_object_name = "category_list"

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        user = self.request.user

        if user.is_organiser:
            queryset      = Lead.objects.filter( organisation = user.userprofile)
        else:
            queryset      = Lead.objects.filter(organisation = user.agent.organisation)
    
        context.update(
            {
                "unassigned_lead_count":queryset.filter(category__isnull=True).count()
            }
        )
        return context


    def get_queryset(self):
        user = self.request.user
        if user.is_organiser:
            queryset      = Category.objects.filter( organisation = user.userprofile)
        else:
            queryset      = Category.objects.filter(organisation = user.agent.organisation)
        return queryset
    


class CategoryDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "leads/category_detail.html"
    context_object_name = "category"
 
    def get_queryset(self):
        user = self.request.user
        if user.is_organiser:
            queryset      = Category.objects.filter( organisation = user.userprofile)
        else:
            queryset      = Category.objects.filter(organisation = user.agent.organisation)
        return queryset


class LeadCategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "leads/lead_category_update.html"
    form_class    = LeadCategoryUpdateForm

    def get_queryset(self):
        user = self.request.user
        if user.is_organiser:
            queryset = Lead.objects.filter(organisation = user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation = user.agent.organisation)
            querset  = queryset.filter(agent__user = user)
        return queryset
    
    def get_success_url(self):
        return reverse("leads:lead-detail", kwargs = {"pk":self.get_object().id})

templates/leads/assign_agent.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content%}
        <a class= "w-full text-black  bg-white-500 hover:text-blue-900 px-3 py-1 rounded-md " href="{% url 'leads:lead-list' %}"> <-Go back</a>
    <div class = "max-w-lg mx-auto">
    
        <h1 class ="text-4xl text-gray-800 mb-5"> Assign agent for this lead </h1>
        <form method="POST" action = ".">
        {% csrf_token %}
        {{ form|crispy}}
        <button type="submit" class ="w-full text-white bg-blue-500 hover:bg-blue-700 px-3 py-1 rounded-md ">submit</button>
    </form>
    </div>
                 
 {% endblock content %}   
    

templates/leads/category_detail.html
{% extends "base.html" %}
{% block content%}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">{{ category.name }}</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
      These are leads under this category </p>
    </div>
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">
            First Name</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
            Last Name</th>
          </tr>
        </thead>
        <tbody>
         
        {% for lead in category.leads.all %}
          <tr>
            <td class="px-4 py-3">
            <a class ="hover:text-blue-500" href ="{% url 'leads:lead-detail' lead.pk %}" > {{ lead.first_name }}</a>
            </td>
            <td class="px-4 py-3"> {{ lead.last_name }}</td>
          </tr>
         
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>


    
{% endblock content%}
    

templates/leads/category_list.html
{% extends "base.html" %}
{% block content%}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Category</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
      These Categories Segements Leads</p>
    </div>
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Name</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Lead Count</th>
          </tr>
        </thead>
        <tbody>
        <tr>
            <td class="px-4 py-3">unassigned</td>
            <td class="px-4 py-3"> {{unassigned_lead_count}} </td>
          </tr>
        {% for category in category_list %}
          <tr>
            <td class="px-4 py-3">
            <a href = "{% url 'leads:category-detail' category.pk %}">{{ category.name }}</a>
            </td>
            <td class="px-4 py-3"> ToDO count </td>
          </tr>
         
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>


    
{% endblock content%}
    

templates/leads/lead_category_update.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}
      <div class="w-1/2 mx-auto">


        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD NAME</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name}} {{lead.last_name}}</h1>
        <div class="flex mb-4">
          <a href="{% url 'leads:lead-detail' lead.pk%}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Description</a>
          <a href="{% url 'leads:lead-category-update' lead.pk %}" class="flex-grow text-blue-500 border-b-2 border-blue-500 py-2 text-lg px-1">Category</a>
          <a href="{% url 'leads:lead-update'  lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
        </div>
      
        <form method="POST" action = ".">
        {% csrf_token %}
          {{ form|crispy}}

        <button class="w-full text-white bg-blue-500 hover:bg-blue-700 px-3 py-1 rounded-md " type="submit">Update</button>
    </form>
        <div class="flex">
          <a href="{% url 'leads:lead-delete' lead.pk %}" class="w-full text-white text-center bg-blue-500 hover:bg-red-700 px-3 py-1 rounded-md ">Delete</a>
          
        </div>
      </div>
  
  

    

    
                 
   {% endblock content %}

templates/leads/lead_create.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content%}

        <a class ="w-full text-black  bg-white-500 hover:text-blue-900 px-3 py-1 rounded-md " href="{% url 'leads:lead-list' %}"> <- Go Back</a>
        
    <div class = "max-w-lg mx-auto">
          <h1 class ="text-4xl text-gray-800">Create a new Lead</h1>
        

        <form class ="mt-6" method="POST">
        {% csrf_token %}
             {{ form|crispy}}

        <button type="submit" class ="w-full text-white bg-blue-500 hover:bg-blue-700 px-3 py-1 rounded-md ">Submit</button>
    </form>
</div>
                 
 {% endblock content %}   
    

templates/leads/lead_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content%}
        <a class= "w-full text-black  bg-white-500 hover:text-blue-900 px-3 py-1 rounded-md " href="{% url 'leads:lead-list' %}"> <-Go back</a>
    <div class = "max-w-lg mx-auto">
        
        <h1 class ="text-4xl text-gray-800"> Are You Sure You Want To Delete This Lead?</h1>
        <form method="POST" action = ".">
        {% csrf_token %}
        {{ form|crispy}}

        <button class ="w-full mt-5 text-center text-white bg-blue-500 hover:bg-red-700 px-3 py-1 rounded-md " type="submit">Delete</button>
    </form>
</div>
                 
 {% endblock content %}   
    

templates/leads/lead_details.html
{% extends "base.html" %}
{% block content %}

      <div class="w-1/2 mx-auto">
  
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD NAME</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name}} {{lead.last_name}}</h1>
        <div class="flex mb-4">
          <a href="{% url 'leads:lead-detail'  lead.pk %}" class="flex-grow text-blue-500 border-b-2 border-blue-500 py-2 text-lg px-1">Description</a>
          <a href="{% url 'leads:lead-category-update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category</a>
          <a href="{% url 'leads:lead-update'  lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
        </div>
        <p class="leading-relaxed mb-4">{{ lead.description}}</p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">First Name</span>
          <span class="ml-auto text-gray-900">{{ lead.first_name}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Age</span>
          <span class="ml-auto text-gray-900">{{lead.age}}</span>
        </div>
        <section class="text-gray-600 body-font overflow-hidden">
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Mobile Number</span>
          <span class="ml-auto text-gray-900">{{ lead.phone_number}}</span>
        </div>
        
         <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Email</span>
          <span class="ml-auto text-gray-900">{{ lead.email}}</span>
        </div>
         <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Date </span>
          <span class="ml-auto text-gray-900">{{ lead.date_added}}</span>
        </div>
        </div>
  

        
       
     


   
    

    
    
{% endblock content %}
    

templates/leads/lead_list.html
{% extends "base.html" %}
{% block content%}

<section class="text-gray-700 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-grey-200"> 
        <div>
            <h1 class="text-4xl text-grey-800">Leads</h1>
        <a class="text-grey-500 hover:text-blue-500" href="{% url 'leads:category-list' %}">
        View Categories
        </a>

        </div>
        {% if request.user.is_organiser %}
    <div>
        <a class="text-grey-500 hover:text-blue-500" href="{% url 'leads:lead-create' %}">create new lead</a>
        </div>
        {% endif %}
    </div>

    <div class="flex flex-wrap -m-4">
     {% for lead in leads %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-blue-100 text-blue-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
            {{lead.first_name}}  {{lead.last_name}} </h2>
            <p class="leading-relaxed text-base">
            {{ lead.description }}</p>
            <a href="{% url 'leads:lead-detail' lead.pk %}" class="mt-3 text-blue-500 inline-flex items-center">
            View This Lead
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}


    {% if unassigned_leads.exists %}

    <div class="mt-5 flex flex-wrap -m-4">
     <div class="p-4 w-full">
       
     <h1 class="text-4xl text-grey-800"> unassigned leads </h1>
     </div>

     {% for lead in unassigned_leads %}
     <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-blue-100 text-blue-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
            {{lead.first_name}}  {{lead.last_name}} </h2>
            <p class="leading-relaxed text-base">
            {{ lead.description }}</p>
            <a href="{% url 'leads:assign-agent' lead.pk %}" class="mt-3 text-blue-500 inline-flex items-center">
            Assign Agent to this lead
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      
    {% endfor %}
    {% endif %}
    </div>
  
    
    </div>
  </div>
</section>

    
   
       <div class="lead">

    
          
          {{ lead.first_name }}
           {{ lead.last_name }} </a>
           {{ lead.age }} 
           
           
           
         
        </div>
    
    
{% endblock content%}
    

templates/leads/lead_update.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}

      <div class="w-1/2 mx-auto">

        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD NAME</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name}} {{lead.last_name}}</h1>
        <div class="flex mb-4">
          <a href="{% url 'leads:lead-detail' lead.pk%}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Description</a>
          <a href="{% url 'leads:lead-category-update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category</a>
          <a href="{% url 'leads:lead-update'  lead.pk %}" class="flex-grow text-blue-500 border-b-2 border-blue-500 py-2 text-lg px-1">Update</a>
        </div>
      
        <form method="POST" >
        {% csrf_token %}
          {{ form|crispy}}

        <button class ="w-full text-white bg-blue-500 hover:bg-blue-700 px-3 py-1 rounded-md "type="submit">Update</button>
    </form>
        <div class="flex">
          <a href="{% url 'leads:lead-delete' lead.pk %}" class ="w-full text-center text-white bg-blue-500 hover:bg-red-700 px-3 py-1 rounded-md ">Delete</a>
          
        </div>

        </div>
      
     
  

    

    
                 
   {% endblock content %}