agents/urls.py
from django.urls import path
from .views import AgentListView , AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name= 'agents'

urlpatterns=[
    path('', AgentListView.as_view(), name='agents-list'),
    path('<int:pk>/' , AgentDetailView.as_view(), name='agents-detail'),
    path('<int:pk>/update/' , AgentUpdateView.as_view(), name='agents-update'),
    path('<int:pk>/delete/' , AgentDeleteView.as_view(), name='agents-delete'),
    path('create/', AgentCreateView.as_view(), name='agents-create'),


    


]

djcrm/urls.py
from django.contrib import admin
from django.contrib.auth.views import (
LoginView, 
LogoutView, 
PasswordResetView, 
PasswordResetDoneView,
PasswordResetConfirmView,
PasswordResetCompleteView
)
from django.urls import path,include
from leads.views import landing_page , LandingPageView, SignupView
from agents.views import AgentListView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPageView.as_view(), name="landing-page"),
    path('leads/', include('leads.urls',namespace="leads")),
    path('agents/', include('agents.urls',namespace="agents")),
    path('signup/',SignupView.as_view(), name="signup"),
    path('reset-password/',PasswordResetView.as_view(), name="reset-password"),
    path('password-reset-done/',PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(), name="password_reset_complete"),


    
    path('login/',LoginView.as_view(), name="login"),
    path('logout/',LogoutView.as_view(), name="logout"),

    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms 
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()

class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name',
        )

agents/views.py
import random
from django.views import generic
from django.views.generic import TemplateView, ListView , DetailView ,CreateView, UpdateView, DeleteView
from django.contrib import messages
from django.shortcuts import render, reverse
from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin
from leads.models import Agent, Lead
from .forms import AgentModelForm
from .mixins import OrganiserAndLoginRequiredMixin

# Create your views here.
class AgentListView(OrganiserAndLoginRequiredMixin, generic.ListView):
    template_name = "agents/agents_list.html"
    
    def get_queryset(self):
        organisation  = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)



class AgentCreateView(OrganiserAndLoginRequiredMixin, generic.CreateView):
    template_name = "agents/agents_create.html"
    form_class    = AgentModelForm

    def get_success_url(self):
        return reverse("agents:agents-list")

    def form_valid(self, form):
        user = form.save(commit= False)
        user.is_agent = True
        user.is_organiser = False
        user.set_password(f"{random.randint(0,10000)}")
        user.save()
        Agent.objects.create(
            user=user,
            organisation = self.request.user.userprofile
           
            
        )
        send_mail(
            subject = "You are giSHEETALven the opportunity to become and agent",
            message = "You are added as an agent in GDCRM. Please login and continue the great work",
            from_email = "admin@test.com",
            recipient_list = [user.email]

        )
        return super(AgentCreateView,self).form_valid(form)

class AgentDetailView(OrganiserAndLoginRequiredMixin, generic.DetailView):
    template_name = 'agents/agents_detail.html'
    def get_queryset(self):
        organisation  = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)



class AgentUpdateView(OrganiserAndLoginRequiredMixin, generic.UpdateView):
    template_name = "agents/agents_update.html"
    form_class    = AgentModelForm

   
    
    def get_queryset(self):
        organisation  = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)


    def get_success_url(self):
        return reverse("agents:agents-list")
    
    def form_valid(self, form):
        form.save()
        messages.info(self.request, "You have successfully updated this lead")
        return super(AgentUpdateView, self).form_valid(form)
    

    



class AgentDeleteView(OrganiserAndLoginRequiredMixin, generic.DeleteView):
    template_name = 'agents/agents_delete.html'
    
    def get_success_url(self):
        return reverse("agents:agents-list")

    def get_queryset(self):
        organisation  = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)

agents/templates/agents/agents_create.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content%}
        <a class ="w-full text-black  bg-white-500 hover:text-blue-900 px-3 py-1 rounded-md " href="{% url 'agents:agents-list' %}"> <-Go back</a>
    
     <div class = "max-w-lg mx-auto"> 
        <h1 class ="text-4xl text-gray-800"> Create a new Agent</h1>
        <form class ="mt-6" method="POST" action = ".">
        {% csrf_token %}
        {{ form|crispy}}

        <button type="submit"  class ="w-full text-white bg-blue-500 hover:bg-blue-700 px-3 py-1 rounded-md ">Submit</button>
    </form>
    </div>
                 
 {% endblock content %}   
    

agents/templates/agents/agents_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content%}
        <a class ="w-full text-black  bg-white-500 hover:text-blue-900 px-3 py-1 rounded-md " href="{% url 'agents:agents-list' %}"> go back</a>
    <div class = "max-w-lg mx-auto">
        
        <h1 class ="text-4xl text-gray-800"> Are You Sure You Want To Delete This Agent?</h1>
        <form method="POST" action = ".">
        {% csrf_token %}
        {{ form|crispy}}

        <button type="submit" class ="w-full mt-5 text-center text-white bg-blue-500 hover:bg-red-700 px-3 py-1 rounded-md ">Delete</button>
    </form>
    </div>
                 
 {% endblock content %}   
    

agents/templates/agents/agents_detail.html
{% extends "base.html" %}
{% block content %}
 
      <div class="w-1/2 mx-auto">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent Name</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.username}}</h1>
        <div class="flex mb-4">
          <a class="flex-grow text-blue-500 border-b-2 border-blue-500 py-2 text-lg px-1">Overview</a>
          <a href="{% url 'agents:agents-update'  agent.pk %}"   class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
        </div>
        <p class="leading-relaxed mb-4"></p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">First Name</span>
          <span class="ml-auto text-gray-900">{{agent.user.first_name}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Last Name</span>
          <span class="ml-auto text-gray-900">{{agent.user.last_name}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Email</span>
          <span class="ml-auto text-gray-900">{{agent.user.email }}</span>
        </div>
       
       
       
        
     
  </div>

   
    

    
    
{% endblock content %}
    

agents/templates/agents/agents_list.html
{% extends "base.html" %}

{% block content %}


  
<section class="text-gray-700 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-grey-200"> 
        <div>
            <h1 class="text-4xl text-grey-800">Agents</h1>
        </div>
    <div>
        <a class="text-grey-500 hover:text-blue-500" href="{% url 'agents:agents-create' %}">create new agent</a>
        </div>
    </div>

    <div class="flex flex-wrap -m-4">
     {% for agent in object_list %}

      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-blue-100 text-blue-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">  {{agent.user.username}}
 </h2>
            <p class="leading-relaxed text-base"></p>
           <a href="{% url 'agents:agents-detail' agent.pk %}" class="mt-3 text-blue-500 inline-flex items-center">View This Agent
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      
    {% endfor %}

    </div>
  </div>
</section>






{% endblock content %}

agents/templates/agents/agents_update.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}

      <div class="w-1/2 mx-auto">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT NAME</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.username}} </h1>
        <div class="flex mb-4">
          <a href="{% url 'agents:agents-detail' agent.pk%}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Description</a>
          <a href="{% url 'agents:agents-update'  agent.pk %}" class="flex-grow text-blue-500 border-b-2 border-blue-500 py-2 text-lg px-1">Update</a>
        </div>
      
        <form method="POST" >
        {% csrf_token %}
        {{ form|crispy}}

        <button class="w-full text-white bg-blue-500 hover:bg-blue-700 px-3 py-1 rounded-md " type="submit">Update</button>
    </form>
        <div class="flex">
          <a href="{% url 'agents:agents-delete'  agent.pk %}"class="w-full text-center text-white bg-blue-500 hover:bg-red-700 px-3 py-1 rounded-md ">Delete</a>
          
        </div>
      </div>
    </div>
  </div>
</section>

  

    

    
                 
   {% endblock content %}